### PR TITLE
chore: Fixed the Hero section which was hiding behind the navbar in small screen

### PR DESCRIPTION
**Pull request by nitin094-hub**
I have fixed the problem in which the hero section was hiding behind the navbar when the screen size is reduced.

### CODE REVIEW

**Comment by Rishabhraghwendra18** [comment]
@nitin094-hub please update your local branch . Using these commands:
```
git remote add upstream https://github.com/Rishabhraghwendra18/hackmoreish.git
git pull upstream main
```
Then make a PR because it looks like your PR is not up-to-date to upstream

**Comment by nitin094-hub** [comment]
Should I make a new pr or update this one itself?

**Comment by nitin094-hub** [comment]
Alright!

**Comment by nitin094-hub** [comment]
do you tell me how can I make a new PR with the same commit?

**Comment by nitin094-hub** [comment]
Can you tell me how can I make a new PR with the same commit?

**Comment by Rishabhraghwendra18** [comment]
> Can you tell me how can I make a new PR with the same commit?

You don't have to make a new PR . Just commit the changes and push to your `fixing-bug` branch . This PR will automatically get's updated

**Comment by nitin094-hub** [comment]
ok

**Pull request closed without merging**
